import React, { useEffect, useState } from 'react';
import { 
  Sparkles, 
  Bug, 
  Clock, 
  Layers, 
  CheckCircle2, 
  AlertTriangle, 
  AlertOctagon, 
  Info, 
  Copy, 
  Download, 
  Share2, 
  ShieldCheck,
  Check,
  Cpu,
  RefreshCw,
  Terminal,
  Zap
} from 'lucide-react';
import confetti from 'canvas-confetti';
import { useToast } from '../context/ToastContext';

export const ReviewPanel = ({ result, isLoading, onReScan }) => {
  const { showToast } = useToast();
  const [copiedMd, setCopiedMd] = useState(false);
  const [activeStep, setActiveStep] = useState(0);

  // Progressive scanning message simulation
  useEffect(() => {
    let interval;
    if (isLoading) {
      setActiveStep(0);
      interval = setInterval(() => {
        setActiveStep((prev) => (prev < 3 ? prev + 1 : prev));
      }, 1200);
    }
    return () => clearInterval(interval);
  }, [isLoading]);

  // Trigger celebration confetti if zero bugs found
  useEffect(() => {
    if (result && (!result.bugs || result.bugs.length === 0)) {
      confetti({
        particleCount: 80,
        spread: 60,
        origin: { y: 0.6 },
        colors: ['#10b981', '#38bdf8', '#818cf8'],
      });
    }
  }, [result]);

  const scanSteps = [
    'Parsing syntax tree and control flow...',
    'Checking security vulnerabilities and memory leaks...',
    'Calculating algorithmic Big-O complexity...',
    'Generating actionable remediation guidelines...',
  ];

  const handleCopyMarkdown = () => {
    if (!result) return;

    let md = `# Code Review & Debug Report\n\n`;
    md += `## 📋 Summary\n${result.summary || 'No summary provided.'}\n\n`;
    md += `## ⏱️ Algorithmic Complexity\n- **Time Complexity:** ${result.timeComplexity || 'N/A'}\n- **Space Complexity:** ${result.spaceComplexity || 'N/A'}\n\n`;
    md += `## 🐛 Identified Issues (${result.bugs?.length || 0})\n\n`;

    if (result.bugs && result.bugs.length > 0) {
      result.bugs.forEach((b, idx) => {
        md += `### ${idx + 1}. ${b.title || 'Issue'} [${(b.severity || 'Medium').toUpperCase()}]\n`;
        md += `**Recommendation:** ${b.recommendation || 'N/A'}\n\n`;
      });
    } else {
      md += `*No critical bugs or vulnerabilities identified in the analyzed snippet.*\n\n`;
    }

    md += `---\n*Generated by BugLens AI*`;

    navigator.clipboard.writeText(md);
    setCopiedMd(true);
    showToast('Markdown report copied to clipboard!', 'success');
    setTimeout(() => setCopiedMd(false), 2500);
  };

  const handleDownloadJSON = () => {
    if (!result) return;
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `buglens-review-${Date.now()}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    showToast('JSON report downloaded successfully', 'info');
  };

  return (
    <div className="glass-panel review-panel-wrapper">
      {/* Panel Header */}
      <div className="panel-header">
        <div className="panel-title-group">
          <div className="panel-title">
            <Sparkles size={18} color="#a855f7" />
            <span>AI Review & Debug Engine</span>
          </div>
        </div>

        {/* Action Controls when results exist */}
        {result && !isLoading && (
          <div className="panel-controls">
            <button
              className="btn btn-outline btn-icon"
              onClick={handleCopyMarkdown}
              title="Copy Report as Markdown"
              aria-label="Copy Markdown"
            >
              {copiedMd ? <Check size={15} color="#10b981" /> : <Copy size={15} />}
            </button>

            <button
              className="btn btn-outline btn-icon"
              onClick={handleDownloadJSON}
              title="Export Report as JSON"
              aria-label="Export JSON"
            >
              <Download size={15} />
            </button>

            <button
              className="btn btn-outline btn-icon"
              onClick={onReScan}
              title="Re-analyze Code"
              aria-label="Re-analyze"
            >
              <RefreshCw size={15} />
            </button>
          </div>
        )}
      </div>

      {/* Main Review Content */}
      <div className="review-content-scroll">
        {/* State 1: Loading / Radar Scanning Animation */}
        {isLoading ? (
          <div className="scanning-state">
            <div className="radar-container">
              <div className="radar-circle radar-circle-1"></div>
              <div className="radar-circle radar-circle-2"></div>
              <div className="radar-sweep"></div>
              <div className="radar-center-dot"></div>
            </div>

            <div>
              <h3 style={{ fontSize: '1.1rem', fontWeight: 700, color: '#f8fafc', marginBottom: '0.35rem' }}>
                Analyzing Code Base
              </h3>
              <p style={{ fontSize: '0.85rem', color: '#94a3b8' }}>
                Gemini AI is performing static, semantic, and complexity analysis...
              </p>
            </div>

            <div className="scanning-steps">
              {scanSteps.map((step, idx) => (
                <div
                  key={idx}
                  className={idx <= activeStep ? 'scanning-step-active' : ''}
                  style={{ opacity: idx <= activeStep ? 1 : 0.4, transition: 'all 0.3s ease' }}
                >
                  {idx <= activeStep ? <CheckCircle2 size={14} /> : <div style={{ width: 14, height: 14 }} />}
                  <span>{step}</span>
                </div>
              ))}
            </div>
          </div>
        ) : result ? (
          /* State 2: Review Results */
          <>
            {/* 1. Summary Card */}
            <div className="summary-card">
              <div className="summary-header">
                <span className="summary-tag">
                  <Cpu size={14} />
                  <span>Executive Analysis Summary</span>
                </span>
                <span
                  style={{
                    fontSize: '0.72rem',
                    padding: '2px 8px',
                    borderRadius: '999px',
                    background: 'rgba(56, 189, 248, 0.15)',
                    color: '#38bdf8',
                    fontWeight: 700,
                  }}
                >
                  AI Evaluated
                </span>
              </div>
              <p className="summary-text">{result.summary || 'Code analyzed successfully.'}</p>
            </div>

            {/* 2. Algorithmic Complexity Metrics */}
            <div className="complexity-grid">
              <div className="complexity-card time">
                <span className="complexity-label">
                  <Clock size={13} color="#818cf8" />
                  <span>Time Complexity</span>
                </span>
                <span className="complexity-value">{result.timeComplexity || 'O(1)'}</span>
              </div>

              <div className="complexity-card space">
                <span className="complexity-label">
                  <Layers size={13} color="#c084fc" />
                  <span>Space Complexity</span>
                </span>
                <span className="complexity-value">{result.spaceComplexity || 'O(1)'}</span>
              </div>
            </div>

            {/* 3. Bug & Security Issues List */}
            <div>
              <div className="bugs-section-header">
                <div className="bugs-title">
                  <Bug size={17} color="#fb7185" />
                  <span>Issues & Vulnerabilities</span>
                </div>
                <span
                  className={`bug-count-badge ${
                    !result.bugs || result.bugs.length === 0 ? 'zero' : ''
                  }`}
                >
                  {result.bugs ? result.bugs.length : 0} Identified
                </span>
              </div>

              <div style={{ marginTop: '0.75rem' }}>
                {result.bugs && result.bugs.length > 0 ? (
                  <div className="bugs-list">
                    {result.bugs.map((bug, index) => {
                      const severity = (bug.severity || 'medium').toLowerCase();
                      let SeverityIcon = AlertTriangle;
                      if (severity === 'critical' || severity === 'high') {
                        SeverityIcon = AlertOctagon;
                      } else if (severity === 'info' || severity === 'low') {
                        SeverityIcon = Info;
                      }

                      return (
                        <div key={index} className={`bug-card ${severity}`}>
                          <div className="bug-card-top">
                            <div className="bug-title">
                              <SeverityIcon
                                size={16}
                                color={
                                  severity === 'critical' || severity === 'high'
                                    ? '#fb7185'
                                    : severity === 'warning' || severity === 'medium'
                                    ? '#fbbf24'
                                    : '#38bdf8'
                                }
                              />
                              <span>{bug.title || `Issue #${index + 1}`}</span>
                            </div>
                            <span className={`severity-tag ${severity}`}>
                              {bug.severity || 'Medium'}
                            </span>
                          </div>

                          {bug.recommendation && (
                            <div className="bug-recommendation-box">
                              <span className="recommendation-label">
                                <ShieldCheck size={12} />
                                <span>Remediation & Fix</span>
                              </span>
                              <span>{bug.recommendation}</span>
                            </div>
                          )}
                        </div>
                      );
                    })}
                  </div>
                ) : (
                  /* Zero Bugs Card */
                  <div className="zero-bugs-card">
                    <div className="zero-bugs-icon">
                      <CheckCircle2 size={28} />
                    </div>
                    <div>
                      <h4 style={{ fontSize: '1.05rem', fontWeight: 700, color: '#34d399' }}>
                        Clean Code! No Critical Issues Found
                      </h4>
                      <p style={{ fontSize: '0.85rem', color: '#94a3b8', marginTop: '0.25rem' }}>
                        Your code passed syntax, security, and algorithmic health checks without flags.
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>
          </>
        ) : (
          /* State 3: Empty Default State */
          <div className="empty-review-state">
            <div className="empty-icon-circle">
              <Zap size={32} />
            </div>
            <h3 className="empty-title">Ready to Review & Debug</h3>
            <p className="empty-desc">
              Write, paste, or upload code on the left, then click{' '}
              <strong style={{ color: '#38bdf8' }}>Review & Debug</strong>. BugLens AI will analyze
              logic errors, memory leaks, security vulnerabilities, and Big-O complexity.
            </p>

            <div className="features-pills">
              <div className="feature-pill">
                <Bug size={13} color="#fb7185" />
                <span>Bug & Leak Detection</span>
              </div>
              <div className="feature-pill">
                <Clock size={13} color="#818cf8" />
                <span>Big-O Time Complexity</span>
              </div>
              <div className="feature-pill">
                <Layers size={13} color="#c084fc" />
                <span>Space Complexity</span>
              </div>
              <div className="feature-pill">
                <ShieldCheck size={13} color="#34d399" />
                <span>Actionable Fixes</span>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
